version: "3.2"
services:
  logzio-otel-collector:
    image: logzio/otel-collector-distro:latest
    ports:
      - "14268:14268"
      - "14269:14269"
      - "14250:14250"
    environment:
      - TRACING_TOKEN=${TRACING_TOKEN}
      - LOGZIO_REGION=${LOGZIO_REGION}
  hotrod:
    image: jaegertracing/example-hotrod:1.28.0
    environment:
      - JAEGER_AGENT_HOST=logzio-otel-collector
    ports:
      - "8080:8080"
      - "8083:8083"
    command: ["all"]
