receivers:
  filelog:
    include: [ "/var/log/system.log" ] # MacOs system logs
    include_file_name: false
    include_file_path: true
    operators:
      - type: move
        from: attributes["log.file.path"]
        to: attributes["log_file_path"]
    attributes:
      type: yotam
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  jaeger:
    protocols:
      thrift_compact:
        endpoint: "0.0.0.0:6831"
      thrift_binary:
        endpoint: "0.0.0.0:6832"
      grpc:
        endpoint: "0.0.0.0:14250"
      thrift_http:
        endpoint: "0.0.0.0:14268"
processors:
  batch:
    send_batch_size: 10000
    timeout: 5s
  resourcedetection/system:
    detectors: [ "system" ]
    system:
      hostname_sources: [ "os" ]
exporters:
  logzio/traces-jaeger:
    account_token: "token"
    region: us
  logzio/logs:
    account_token: "token"
    region: us

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [ batch ]
      exporters: [logzio/logs]
    traces:
      receivers: [ otlp,jaeger ]
      processors: [ batch ]
      exporters: [ logzio/traces-jaeger ]
  telemetry:
    logs:
      level: "debug"