name: Format check

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]
jobs:
  fmt:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: echo
        run: |
          echo runing make format-components
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: go fmt
        run: make format-components

