name: lint check

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]
jobs:
  test-exporters:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: echo
        run: |
          echo runing make lint-components
      - uses: actions/checkout@v2
      - name: lint
        run: make lint-components

