name: publish artifacts on a new release
on:
  release:
    types: [published]
jobs:
  publish_artifacts:
    strategy:
      matrix:
        os_arch: [ darwin_amd64, linux_amd64, linux_arm64, linux_arm, windows_amd64  ]
    name: publish artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Install builder
        run: make install-builder
        working-directory: ./otelbuilder
      - name: build artifacts
        run: make otelcol-logzio-${{ matrix.os_arch }}
        working-directory: ./otelbuilder
      - name: upload artifacts to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}
