name: build atrifacts
on:
  release:
    types: [published]
jobs:
  publish_artifacts:
    strategy:
      matrix:
        os_arch: [ darwin_amd64, linux_amd64, linux_arm64, linux_arm  ]
    name: publish artifacts
    runs-on: macos-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Install go tools
        run: make install-tools
      - name: Install builder
        run: make install-builder
        working-directory: ./otelbuilder
      - name: build artifacts
        run: make otelcol-logzio-${{ matrix.os_arch }}
        working-directory: ./otelbuilder
      - name: mkdir
        run: mkdir -p ./artifacts
        working-directory: ./otelbuilder/cmd
      - name: mv binary
        run: mv otelcol-logzio-${{ matrix.os_arch }} ./artifacts
        working-directory: ./otelbuilder/cmd
      - name: compress
        run: tar -czf otelcol-logzio-${{ matrix.os_arch }}.tar.gz artifacts
        working-directory: ./otelbuilder/cmd
      - name: upload artifacts to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.tar.gz
            ./otelbuilder/cmd/artifacts/otelcol-logzio-${{ matrix.os_arch }}



