name: Publish artifacts on a new release windows
on:
  release:
    types: [published]
jobs:
  publish_artifacts:
    strategy:
      matrix:
        os_arch: [ windows_amd64  ]
    name: publish artifacts
    runs-on: macos-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      - name: Install go tools
        run: make install-tools
      - name: Install builder
        run: make install-builder
        working-directory: ./otelbuilder
      - name: build artifacts
        run: make otelcol-logzio-${{ matrix.os_arch }}
        working-directory: ./otelbuilder
      - name: compress artifacts
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: ./otelbuilder/cmd
          files: |
            ./otelcol-logzio-${{ matrix.os_arch }}.exe
          outPath: ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.tar.gz
      - name: upload artifacts to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.exe
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.tar.gz



