name: Publish artifacts on a new release (Windows on Ubuntu)
on:
  release:
    types: [published]

jobs:
  publish_artifacts:
    name: Publish Windows artifacts on Ubuntu
    runs-on: macos-latest

    strategy:
      matrix:
        os_arch: [windows_amd64]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install go tools
        run: make install-tools

      - name: Install builder
        working-directory: ./otelbuilder
        run: make install-builder

      - name: Build Windows binary
        working-directory: ./otelbuilder
        run: make otelcol-logzio-${{ matrix.os_arch }}

      - name: Compress .exe to tar.gz
        run: |
          tar czf \
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.tar.gz \
            -C ./otelbuilder/cmd \
            otelcol-logzio-${{ matrix.os_arch }}.exe

      - name: Install zip utility
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Compress .exe to zip
        run: |
          zip -j \
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.zip \
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.exe

      - name: Upload artifacts to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.exe
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.tar.gz
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.zip
