name: Publish artifacts on a new release
on:
  release:
    types: [published]

jobs:
  publish_artifacts:
    name: Publish artifacts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os_arch: [darwin_amd64, darwin_arm64, linux_amd64, linux_arm64]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install go tools
        run: make install-tools

      - name: Install builder
        working-directory: ./otelbuilder
        run: make install-builder

      - name: Build artifacts
        working-directory: ./otelbuilder
        run: make otelcol-logzio-${{ matrix.os_arch }}

      - name: Compress artifact with built-in tar
        run: |
          tar czf \
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.tar.gz \
            -C ./otelbuilder/cmd \
            otelcol-logzio-${{ matrix.os_arch }}

      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}.tar.gz
            ./otelbuilder/cmd/otelcol-logzio-${{ matrix.os_arch }}
