name: Test-mcomponents

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]
jobs:
  test-exporters:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: test
        run: |
          echo runing make test-components
      - uses: actions/checkout@v2
      - name: go test
        run: make test-components

