name: test components

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]
jobs:
  test-exporters:
    strategy:
      matrix:
        exporters: [logzioexporter]
        os: [ubuntu-latest, windows-latest, macos-12, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: test
        run: |
          echo ${{ matrix.exporters }}
      - uses: actions/checkout@v2
      - name: go test
        working-directory: ./logzio/exporter/${{ matrix.exporters }}
        run: go test -race -v -covermode=atomic -coverprofile=coverage.out

